-- Foundation B, migration 006: hymns and music.

-- `hymns` is the SOLE table in this schema without a ward_id, documented as the one
-- exception to CLAUDE.md rule 1. The hymnbook is identical for every ward, so scoping it
-- per ward would duplicate 341 rows per ward for no benefit.
--
-- Plan C's ward-isolation test skips exactly one table. Keep that skip list at one entry so
-- a future table that forgets ward_id fails the test instead of quietly joining the list.
create table hymns (
  id         integer primary key generated by default as identity,
  number     integer not null unique,
  title      text not null,
  topic_tags text[] not null default '{}'
);

create table hymn_selections (
  id           uuid primary key default gen_random_uuid(),
  ward_id      uuid not null references wards (id) on delete cascade,
  sunday_id    uuid,
  hymn_type    text check (hymn_type in ('opening', 'sacrament', 'closing')),
  hymn_number  integer,
  hymn_title   text,
  selected_by  uuid,
  ai_suggested boolean not null default false,
  created_at   timestamptz not null default now(),
  foreign key (sunday_id, ward_id) references sundays (id, ward_id) on delete cascade,
  foreign key (selected_by, ward_id) references users (id, ward_id)
);

create table musical_numbers (
  id          uuid primary key default gen_random_uuid(),
  ward_id     uuid not null references wards (id) on delete cascade,
  sunday_id   uuid,
  performer   text,
  piece_title text,
  notes       text,
  created_at  timestamptz not null default now(),
  foreign key (sunday_id, ward_id) references sundays (id, ward_id) on delete cascade
);
