-- Phase 3B, migration 027: ward conference, and the meeting/Fast-Sunday split.
--
--   Part 1  the `type` CHECK recreated with 'ward_conference'
--   Part 2  backfill — correct the rows that a cancelled meeting should never have had
--   Part 3  the conductor CHECK, making "a conductor on a Sunday with no meeting" unrepresentable
--
-- The background. `FAST_SUNDAY_DISPLACING_TYPES` in types/domain.ts answered two questions with
-- one list: "this Sunday cannot BE Fast Sunday" and "this Sunday holds no sacrament meeting".
-- The two sets coincided, so nothing had forced them apart. 'ward_conference' forces them apart:
-- it cannot be Fast Sunday, yet it holds a completely ordinary meeting. `holiday` forces them
-- apart from the other side — a ward marking Christmas Sunday as a holiday still meets.
--
-- After this migration, exactly two types hold no meeting: 'stake_conference' and
-- 'general_conference'. That is what Part 2 corrects for and Part 3 enforces.
--
-- ORDER MATTERS. The backfill must run BEFORE the conductor CHECK is added, or the ALTER fails
-- against the rows the backfill exists to fix.


-- ============================================================================
-- Part 1 — the type CHECK
-- ============================================================================
--
-- Migration 004 declared this constraint INLINE on the column, so its name was generated by
-- Postgres rather than chosen. The name is looked up rather than assumed: a `drop constraint if
-- exists` against a guessed name would succeed silently, leave the old constraint in force, and
-- the first insert of 'ward_conference' would fail in production instead of here (CLAUDE.md
-- rule 7 — no silent failures).
--
-- This list must stay in step with SUNDAY_TYPES in types/domain.ts. If it drifts, the database
-- accepts a value TypeScript rejects, and the row comes back through toEnumValue() as a throw on
-- a page render. Adding a type is a two-file change, always.

do $$
declare
  constraint_name text;
begin
  select conname
    into constraint_name
    from pg_constraint
   where conrelid = 'sundays'::regclass
     and contype = 'c'
     and pg_get_constraintdef(oid) like '%general_conference%';

  if constraint_name is null then
    raise exception
      'No CHECK constraint on sundays governs `type`. Migration 004 and this file have drifted.';
  end if;

  execute format('alter table sundays drop constraint %I', constraint_name);
  raise notice 'Dropped the old sundays type CHECK (%)', constraint_name;
end;
$$;

alter table sundays
  add constraint sundays_type_check
    check (type in ('standard', 'fast_sunday', 'stake_conference', 'general_conference',
                    'holiday', 'ward_conference', 'special'));


-- ============================================================================
-- Part 2 — backfill
-- ============================================================================
--
-- Every existing 'stake_conference' and 'general_conference' Sunday carries state it should
-- never have had: a conductor assigned by the rotation, organization conducting rows, speaking
-- slots, and speakers moved along the pipeline. Those rows predate the rule; they are corrected
-- here, once, before the constraint makes them impossible.
--
-- This runs against the LINKED HOSTED PROJECT (CLAUDE.md §9 — there is no local stack), so each
-- step reports its row count. An operator has to be able to see what this touched.

do $$
declare
  affected integer;
begin
  -- DELETED, not nulled. A null user_id already means "this organization's rotation reaches this
  -- Sunday but the position is unfilled" (migration 024, Part 4). "There is no meeting at all" is
  -- a different fact, and the absence of the row is how it is written down.
  delete from sunday_org_conducting
   where sunday_id in (
           select id from sundays
            where type in ('stake_conference', 'general_conference')
         );
  get diagnostics affected = row_count;
  raise notice 'Deleted % organization conducting row(s) on Sundays with no meeting', affected;

  -- REVERTED, never deleted. A speaker returned to the planning stage keeps their record and
  -- does not count as a talk that was given; deleting the assignment would erase somebody's
  -- work (03-calendar.md §Pitfall 5).
  update assignments
     set pipeline_stage = 'plan'
   where pipeline_stage <> 'plan'
     and sunday_id in (
           select id from sundays
            where type in ('stake_conference', 'general_conference')
         );
  get diagnostics affected = row_count;
  raise notice 'Reverted % assignment(s) to the planning stage', affected;

  update sundays
     set conducting_user_id = null,
         speaking_slots = 0
   where type in ('stake_conference', 'general_conference')
     and (conducting_user_id is not null or speaking_slots <> 0);
  get diagnostics affected = row_count;
  raise notice 'Cleared the conductor and speaking slots on % Sunday(s) with no meeting', affected;
end;
$$;


-- ============================================================================
-- Part 3 — the conductor CHECK
-- ============================================================================
--
-- Why it exists: a conductor on a Sunday that holds no meeting is not a state any user action
-- should be able to reach, and until now nothing stopped one being written. Structural rather
-- than procedural, matching how this schema already enforces ward scope with composite foreign
-- keys instead of application checks.
--
-- THE CONSEQUENCE FOR THE CALLER: lib/calendar/queries.ts must clear conducting_user_id in the
-- SAME UPDATE statement that changes the type to one of these. A patch that changes the type and
-- leaves the conductor for a second statement raises here — which is the intended behaviour, a
-- loud failure rather than a silent wrong answer.
--
-- sunday_org_conducting gets NO equivalent constraint, and that was DECIDED, not forgotten. A
-- constraint there cannot see the Sunday's type, so it would have to be a trigger — and this
-- repo has no triggers at all: every invariant in SQL is either a constraint or an explicitly
-- called plpgsql function. Adding trigger machinery for one rule is the wrong trade. That rule
-- is enforced in lib/calendar/queries.ts and in PATCH /api/sundays/[id]/org-conducting, which
-- refuses with a 409.

alter table sundays
  add constraint sundays_no_conductor_without_meeting
    check (conducting_user_id is null
           or type not in ('stake_conference', 'general_conference'));

comment on constraint sundays_no_conductor_without_meeting on sundays is
  'A Sunday that holds no sacrament meeting has no conductor. Callers must clear conducting_user_id in the same UPDATE that sets the type. sunday_org_conducting has no equivalent constraint on purpose - it would need a trigger, and that rule lives in lib/calendar/queries.ts instead.';
